-- Create the 'session' table
CREATE TABLE IF NOT EXISTS public.session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creator_id VARCHAR(255),
    duration INTEGER,
    meeting_link VARCHAR(255),
    resources_link VARCHAR(255),
    start TIMESTAMP(6) WITHOUT TIME ZONE,
    tags VARCHAR(255),
    title VARCHAR(255)
);
